import 'package:space_app/core/app_assets.dart';
import '../../model/planet_details_model.dart';

final List<PlanetDetailsModel> planetsDetails = [
  PlanetDetailsModel(
    name: "Mercury",
    image: AppAssets.mercury,
    model3d: "mercury.glb",
    title: "Mercury: The Closest Planet",
    about: "The Sun is the heart of our solar system, a massive ball of plasma that provides heat, light, and energy to everything within its gravitational pull.",
    distanceFromSunKm: "57909227",
    lengthOfDayHours: "1407.6",
    orbitalPeriodYears: "0.24",
    radiusKm: "2439.7",
    massKg: "3.301e23",
    gravity: "3.7",
    surfaceAreaKm2: "7.48e7",
  ),
  PlanetDetailsModel(
    name: "Venus",
    image: AppAssets.venus,
    model3d: "venus.glb",
    title: "Venus: Earth's Toxic Twin",
    about: "Venus is often referred to as Earth's twin due to its similar size and composition.",
    distanceFromSunKm: "108209072",
    lengthOfDayHours: "5832.2",
    orbitalPeriodYears: "0.62",
    radiusKm: "6051.8",
    massKg: "4.867e24",
    gravity: "8.87",
    surfaceAreaKm2: "4.60e8",
  ),
  PlanetDetailsModel(
    name: "Earth",
    image: AppAssets.earth,
    model3d: "earth.glb",
    title: "Earth: Our Blue Marble",
    about: "Earth is the only known planet in the universe that supports life.",
    distanceFromSunKm: "149598026",
    lengthOfDayHours: "23.93",
    orbitalPeriodYears: "1",
    radiusKm: "6371",
    massKg: "5.972e24",
    gravity: "9.81",
    surfaceAreaKm2: "5.10e8",
  ),
  PlanetDetailsModel(
    name: "Mars",
    image: AppAssets.mars,
    model3d: "mars.glb",
    title: "Mars: The Red Planet",
    about: "Mars, often called the Red Planet due to its reddish hue caused by iron oxide.",
    distanceFromSunKm: "227943824",
    lengthOfDayHours: "24.62",
    orbitalPeriodYears: "1.88",
    radiusKm: "3389.5",
    massKg: "6.39e23",
    gravity: "3.71",
    surfaceAreaKm2: "1.45e8",
  ),
  PlanetDetailsModel(
    name: "Jupiter",
    image: AppAssets.jupiter,
    model3d: "jupiter.glb",
    title: "Jupiter: The Gas Giant",
    about: "Jupiter is the largest planet in our solar system.",
    distanceFromSunKm: "778547669",
    lengthOfDayHours: "9.92",
    orbitalPeriodYears: "11.86",
    radiusKm: "69911",
    massKg: "1.898e27",
    gravity: "24.79",
    surfaceAreaKm2: "6.21e15",
  ),
  PlanetDetailsModel(
    name: "Saturn",
    image: AppAssets.saturn,
    model3d: "saturn.glb",
    title: "Saturn: The Ringed Planet",
    about: "Saturn is best known for its spectacular rings.",
    distanceFromSunKm: "1426666422",
    lengthOfDayHours: "10.66",
    orbitalPeriodYears: "29.46",
    radiusKm: "58232",
    massKg: "5.683e26",
    gravity: "10.44",
    surfaceAreaKm2: "4.27e15",
  ),
  PlanetDetailsModel(
    name: "Uranus",
    image: AppAssets.uranus,
    model3d: "uranus.glb",
    title: "Uranus: The Tilted Planet",
    about: "Uranus is an ice giant with a unique axial tilt.",
    distanceFromSunKm: "2870990000",
    lengthOfDayHours: "17.24",
    orbitalPeriodYears: "84.01",
    radiusKm: "25362",
    massKg: "8.681e25",
    gravity: "8.69",
    surfaceAreaKm2: "8.1e15",
  ),
  PlanetDetailsModel(
    name: "Neptune",
    image: AppAssets.neptune,
    model3d: "neptune.glb",
    title: "Neptune: The Distant World",
    about: "Neptune is the farthest planet from the Sun.",
    distanceFromSunKm: "4498252900",
    lengthOfDayHours: "16.11",
    orbitalPeriodYears: "164.8",
    radiusKm: "24622",
    massKg: "1.024e26",
    gravity: "11.15",
    surfaceAreaKm2: "7.65e15",
  ),
  PlanetDetailsModel(
    name: "Sun",
    image: AppAssets.sun,
    model3d: "sun.glb",
    title: "The Sun: Our Solar System's Star",
    about: "The Sun is the heart of our solar system, a massive ball of plasma that provides heat, light, and energy to everything within its gravitational pull.",
    distanceFromSunKm: "0",
    lengthOfDayHours: "0",
    orbitalPeriodYears: "0",
    radiusKm: "695700",
    massKg: "1.989e30",
    gravity: "274",
    surfaceAreaKm2: "6.09e12",
  ),
];
